markdown: kramdown
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
title: HMM's blog
description: HMM's blog, powered by Jekyll...
author: richard.hmm

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir: