auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: blog
url: http://richardhmm.github.io/blog/
feed: /atom.xml
author_info: <a href="http://richardhmm.github.io/blog/">richardhmm</a>
